"""Large-scale test on WBM initial structures (geometry-only, elements anonymized).

WBM was generated by element substitution from MP prototypes, so many element
SETS overlap our (MPTrj-trained) model's training sets. We therefore report two
buckets: element sets our split EXCLUDED from training (gid%10==0, "unseen-set")
vs the rest ("seen-set") -- the unseen-set bucket is the honest generalization
number.

Usage:
  uv run python scripts/evaluate_wbm.py <ckpt...> --xyz Data/WBM/<file>.extxyz \
      [--sample 3000] [--batch 512]
"""

from __future__ import annotations

import argparse
import itertools

import numpy as np
import torch
from ase.io import iread
from tqdm import tqdm

from typeid2elem.data import collate, N_CLASSES
from typeid2elem.descriptors import compute_features
from typeid2elem.inference import fuse_logp, load_models
from typeid2elem.io import snapshot_from_atoms
from typeid2elem.preprocess import group_id


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("ckpt", nargs="+")
    ap.add_argument("--parquet", nargs="+", required=True)
    ap.add_argument("--cse-json", default=None,
                    help="wbm-computed-structure-entries.json.bz2 -> evaluate "
                         "RELAXED structures (parquets then only supply the "
                         "unique_prototype filter)")
    ap.add_argument("--sample", type=int, default=4000)
    ap.add_argument("--batch", type=int, default=512)
    ap.add_argument("--fuse", default="conf",
                    choices=["logmean", "probmean", "conf", "median"])
    args = ap.parse_args()

    import pandas as pd
    from ase import Atoms

    def _atoms(st):
        lat = np.array([np.asarray(r) for r in st["lattice"]["matrix"]], dtype=float)
        xyz = np.array([np.asarray(s["xyz"]) for s in st["sites"]], dtype=float)
        syms = [s["species"][0]["element"] for s in st["sites"]]
        return Atoms(symbols=syms, positions=xyz, cell=lat, pbc=True)

    def row_iter():
        if args.cse_json:
            protos = set()
            for pq in args.parquet:
                d = pd.read_parquet(pq, columns=["material_id", "unique_prototype"])
                protos |= set(d[d.unique_prototype].material_id)
            df = pd.read_json(args.cse_json)
            df = df[df.material_id.isin(protos)]
            df = df.sample(n=min(args.sample, len(df)), random_state=0)
            for cse in df.computed_structure_entry:
                yield _atoms(cse["structure"])
            return
        per_shard = args.sample // len(args.parquet)
        for pq in args.parquet:
            df = pd.read_parquet(pq, columns=["unique_prototype", "initial_structure"])
            df = df[df.unique_prototype]
            df = df.sample(n=min(per_shard, len(df)), random_state=0)
            for st in df.initial_structure:
                yield _atoms(st)

    models = [m.cuda() for m in load_models(args.ckpt)]
    feats, labels, unseen = [], [], []
    for atoms in tqdm(row_iter(), total=args.sample, unit="struct", mininterval=10):
        try:
            snap, zs = snapshot_from_atoms(atoms)
            if snap.n_types < 2 or snap.n_types > 8 or zs.max() > 94:
                continue
            f = compute_features(snap, with_env=True)
        except Exception:
            continue
        feats.append({k: torch.from_numpy(v.astype(
                          np.int64 if k == "env_t" else np.float32))
                      for k, v in f.items()}
                     | {"labels": torch.from_numpy(zs) - 1})
        labels.append(zs)
        unseen.append(group_id(tuple(snap.orig_type_labels)) % 10 == 0)

    buckets = {"unseen-set": [], "seen-set": []}
    with torch.no_grad():
        for i in range(0, len(feats), args.batch):
            chunk = feats[i:i + args.batch]
            batch = collate(chunk)
            batch = {k: v.cuda() for k, v in batch.items()}
            logp = fuse_logp(
                torch.stack([m(batch).log_softmax(-1) for m in models]),
                args.fuse)
            for j, (lp, item) in enumerate(zip(logp, chunk)):
                t = len(item["labels"])
                ranks = (lp[:t].argsort(-1, descending=True) ==
                         item["labels"][:, None].cuda()).float().argmax(-1) + 1
                buckets["unseen-set" if unseen[i + j] else "seen-set"].append(
                    ranks.cpu().numpy())

    print(f"\nWBM sample: {len(feats)} structures, "
          f"{sum(len(r) for b in buckets.values() for r in b)} type-ids")
    for name, rank_lists in buckets.items():
        if not rank_lists:
            continue
        r = np.concatenate(rank_lists)
        print(f"  {name:<11} n={len(r):>6}  top1={np.mean(r <= 1):.1%} "
              f"top3={np.mean(r <= 3):.1%} top5={np.mean(r <= 5):.1%} "
              f"median rank={np.median(r):.0f}")


if __name__ == "__main__":
    main()
